# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - id: linux-build
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      #- arm64
      - amd64
  # - id: darwin-build
  #   env:
  #     - CGO_ENABLED=0
  #   goos:
  #     - darwin
  #   goarch:
  #     - arm64
  #     - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
snapshot:
  name_template: "0.1-{{ .Env.GIT_REVS }}"
# to build rpm:
# goreleaser release --skip-publish --snapshot
nfpms:
  - description: "Temporary rest api that directly inserts data into mysql of handle server"
    maintainer: "Nicolas Franck <nicolas.franck@ugent.be"
    formats:
      - "rpm"
    builds:
      - linux-build
    release: 1
    license: "BSD"
    bindir: "/opt/handle-server-api"
    contents:
      - src: "etc/systemd/handle-server-api.service"
        dst: "/etc/systemd/system/handle-server-api.service"
        type: "config"
        file_info:
          mode: 0755
          owner: "root"
          group: "root"
      - dst: "/var/log/handle-server-api"
        type: "dir"
        file_info:
          mode: 0775
          owner: "biblio"
          group: "biblio"
    scripts:
      # cf. https://github.com/goreleaser/nfpm/blob/main/rpm/rpm.go#L280
      # postinstall -> %post
      postinstall: "etc/rpm/postinstall.sh"
      # preremove -> %preun
      preremove: "etc/rpm/preun.sh"
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
